### PR TITLE
Separate connection pooling from mutex handling (fixes #10)

### LINKED ISSUE #10: Separate connection pooling from mutex {un,}locking
The [godoc example](https://godoc.org/github.com/hjr265/redsync.go/redsync#example-Mutex) (and all other New\* functions) require passing Redis credentials/connections everytime when acquiring a mutex.

Instead of that, an API that separates connections from mutexes seems much more usable. For example:

``` go
// redsync.New returns *RedSync
redsync := redsync.New([]net.Addr{
    &net.TCPAddr{Port: 6379},
    &net.TCPAddr{Port: 6380},
})

lock, err := redsync.Lock("foo")
if err != nil {
    // success!
}

redsync.Unlock(lock)
```

This way, a single `RedSync` instance could be shared across the codebase without dealing with connection parameters everywhere. What do you think?

### PR DESCRIPTION
**Pull request by dcelasun**
I've introduced a new API as discussed in #10. There is a problem though, the tests *always* fail for me, with or **without** this PR. I'm running it with `go test ./redsync/mutext_test.go` and it fails with:

```
--- FAIL: TestMutex (24.60s)
        mutex_test.go:84: failed to acquire lock
FAIL
FAIL    command-line-arguments  24.670s
```

I'm not sure why this is happenning. Any ideas?

### CODE REVIEW

**Comment by hjr265** [comment]
@dcelasun Thanks for this pull request. I tested it locally and it works fine (both with and without this PR). 

```
=== RUN   TestMutex
--- PASS: TestMutex (5.17s)
=== RUN   TestMutexWithRedSync
--- PASS: TestMutexWithRedSync (4.15s)
=== RUN   ExampleMutex
--- PASS: ExampleMutex (0.00s)
PASS
ok  	github.com/hjr265/redsync.go/redsync	9.713s
```

Were you able to figure out why it might be failing on your end?

**Comment by dcelasun** [comment]
No idea, it's still failing for me. I'm using go 1.5.3 on Linux. Maybe it's platform specific?

**Comment by dcelasun** [comment]
OK, I tested this on a clean machine where neither Go nor Redis were installed before. Here is the test output:

```
$ go test ./redsync
--- FAIL: TestMutex (24.61s)
        mutex_test.go:84: failed to acquire lock
--- FAIL: TestMutexWithRedSync (24.63s)
        mutex_test.go:126: failed to acquire lock
--- FAIL: ExampleMutex (8.20s)
panic: failed to acquire lock [recovered]
        panic: failed to acquire lock

goroutine 1 [running]:
testing.runExample.func2(0xece328b03, 0xc8211fb242, 0x793240, 0xc820082130, 0xc820082008, 0xc820060660, 0x669340, 0xc, 0x6c8c58, 0x0, ...)
        /usr/lib/go/src/testing/example.go:93 +0x3f9
github.com/hjr265/redsync.go/redsync_test.ExampleMutex()
        /home/testing/go/src/github.com/hjr265/redsync.go/redsync/example_test.go:22 +0x32f
testing.runExample(0x669340, 0xc, 0x6c8c58, 0x0, 0x0, 0x0)
        /usr/lib/go/src/testing/example.go:98 +0x3cb
testing.RunExamples(0x6c8ca0, 0x78cc80, 0x1, 0x1, 0x1)
        /usr/lib/go/src/testing/example.go:36 +0x31b
testing.(*M).Run(0xc820047ef8, 0x6c8c80)
        /usr/lib/go/src/testing/testing.go:495 +0xac
github.com/hjr265/redsync.go/redsync_test.TestMain(0xc820047ef8)
        /home/testing/go/src/github.com/hjr265/redsync.go/redsync/mutex_test.go:36 +0x318
main.main()
        github.com/hjr265/redsync.go/redsync/_test/_testmain.go:58 +0x113

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /usr/lib/go/src/runtime/asm_amd64.s:1721 +0x1

goroutine 21 [chan send]:
github.com/hjr265/redsync.go/redsync_test.TestMutex.func1(0xc8200604e0, 0xc820060480)
        /home/testing/go/src/github.com/hjr265/redsync.go/redsync/mutex_test.go:61 +0x199
created by github.com/hjr265/redsync.go/redsync_test.TestMutex
        /home/testing/go/src/github.com/hjr265/redsync.go/redsync/mutex_test.go:78 +0xad

goroutine 22 [chan send]:
github.com/hjr265/redsync.go/redsync_test.TestMutex.func1(0xc8200604e0, 0xc820060480)
        /home/testing/go/src/github.com/hjr265/redsync.go/redsync/mutex_test.go:61 +0x199
created by github.com/hjr265/redsync.go/redsync_test.TestMutex
        /home/testing/go/src/github.com/hjr265/redsync.go/redsync/mutex_test.go:78 +0xad

goroutine 27 [chan send]:
github.com/hjr265/redsync.go/redsync_test.TestMutexWithRedSync.func1(0xc8201d0800, 0xc820060600, 0xc8200605a0)
        /home/testing/go/src/github.com/hjr265/redsync.go/redsync/mutex_test.go:103 +0x1c2
created by github.com/hjr265/redsync.go/redsync_test.TestMutexWithRedSync
        /home/testing/go/src/github.com/hjr265/redsync.go/redsync/mutex_test.go:120 +0xe9

goroutine 24 [chan send]:
github.com/hjr265/redsync.go/redsync_test.TestMutex.func1(0xc8200604e0, 0xc820060480)
        /home/testing/go/src/github.com/hjr265/redsync.go/redsync/mutex_test.go:61 +0x199
created by github.com/hjr265/redsync.go/redsync_test.TestMutex
        /home/testing/go/src/github.com/hjr265/redsync.go/redsync/mutex_test.go:78 +0xad

goroutine 28 [chan send]:
github.com/hjr265/redsync.go/redsync_test.TestMutexWithRedSync.func1(0xc8201d0800, 0xc820060600, 0xc8200605a0)
        /home/testing/go/src/github.com/hjr265/redsync.go/redsync/mutex_test.go:103 +0x1c2
created by github.com/hjr265/redsync.go/redsync_test.TestMutexWithRedSync
        /home/testing/go/src/github.com/hjr265/redsync.go/redsync/mutex_test.go:120 +0xe9

goroutine 29 [chan send]:
github.com/hjr265/redsync.go/redsync_test.TestMutexWithRedSync.func1(0xc8201d0800, 0xc820060600, 0xc8200605a0)
        /home/testing/go/src/github.com/hjr265/redsync.go/redsync/mutex_test.go:103 +0x1c2
created by github.com/hjr265/redsync.go/redsync_test.TestMutexWithRedSync
        /home/testing/go/src/github.com/hjr265/redsync.go/redsync/mutex_test.go:120 +0xe9
FAIL    github.com/hjr265/redsync.go/redsync    57.730s
```

If I only run `mutex_test.go`, the panic goes away, but the test still fails:
```
$ go test ./redsync/mutex_test.go
--- FAIL: TestMutex (24.62s)
        mutex_test.go:84: failed to acquire lock
--- FAIL: TestMutexWithRedSync (24.62s)
        mutex_test.go:126: failed to acquire lock
FAIL
FAIL    command-line-arguments  49.514s
```

At this point, I'm pretty much out of ideas. Thoughts?

**Comment by hjr265** [comment]
I have a feeling this is related to the package that is being used to start those test Redis instances. My GOPATH probably has an old version. The tests also fail in Drone. I will take a look at this and figure out a fix asap.

**Comment by hjr265** [comment]
@dcelasun Thanks for all your help. The issue was related to the tempredis package and how RedSync tests were using it. Tests are passing now: https://drone.io/github.com/hjr265/redsync.go/17

**Comment by dcelasun** [comment]
Thanks for the fix, the tests now pass on my machine as well!

**Pull request merged**
